spring.cloud.bootstrap.enabled=true
logging:
    level:
        org.springframework.cloud.config: DEBUG
        org.springframework.cloud.config.server: DEBUG
        org.springframework.cloud.config.server.environment: DEBUG
        org.springframework.cloud.config.server.resource: DEBUG
        org.eclipse.jgit: DEBUG
        org.springframework.web: DEBUG
        org.eclipse.jgit: TRACE
