server:
  port: 8888

spring:
  application:
    name: msl-config-server

spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/nesanmano/cloud-config-server.git
            default-label: main
            search-paths:
              - "*/"
